language: cpp

matrix:
  include:
  - os: linux
    name: "MPI-Linux SMP"
    dist: xenial
    script:
    - sudo apt-get update && sudo apt-get install -y mpich libmpich-dev
    - ./build LIBS mpi-linux-x86_64 smp -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla || exit 1
    - make -C mpi-linux-x86_64-smp/tmp -j3 all-test-tests all-test-examples OPTS="-g"
    - make -C mpi-linux-x86_64-smp/tmp test-tests test-examples TESTOPTS="+setcpuaffinity"

  - os: osx
    name: "NetLRTS-Darwin"
    script:
    - ./build LIBS netlrts-darwin-x86_64 -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla || exit 1
    - make -C netlrts-darwin-x86_64/tmp -j3 all-test-tests all-test-examples OPTS="-g"
    - make -C netlrts-darwin-x86_64/tmp test-tests test-examples TESTOPTS="++local"

  - os: windows
    name: "NetLRTS-Win"
    script:
    - rm -rf C:/tools/msys64
    - choco upgrade -y msys2
    - export msys2='cmd //C RefreshEnv.cmd '
    - export msys2+='& set MSYS=winsymlinks:nativestrict '
    - export msys2+='& C:\\tools\\msys64\\msys2_shell.cmd -defterm -no-start'
    - export mingw64="$msys2 -mingw64 -full-path -here -c \$\* --"
    - export msys2+=" -msys2 -c \$\* --"
    - $msys2 pacman --sync --noconfirm --needed autoconf libtool automake make autoconf-archive pkg-config
    - taskkill //IM gpg-agent.exe //F  # https://travis-ci.community/t/4967
    - export PATH=/C/tools/msys64/mingw64/bin:$PATH
    - $mingw64 src/arch/win/travis.sh ./build AMPI netlrts-win-x86_64 -j3 --without-romio --with-production --enable-error-checking --enable-lbuserdata
    - $mingw64 src/arch/win/travis.sh make -C netlrts-win-x86_64/tmp -j3 all-test-tests
    - $mingw64 src/arch/win/travis.sh make -C netlrts-win-x86_64/tests/charm++ test
