language: cpp

# Necessary for Windows builds - do not convert LF to CRLF:
git:
  autocrlf: false

before_install:
  - |
      if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
        git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.rst$)|(^doc/)' || {
          echo "Only docs were updated, stopping build process."
          exit
        }
      fi

matrix:
  include:
  - os: linux
    name: "MPI-Linux SMP"
    dist: xenial
    script:
    - sudo apt-get update && sudo apt-get install -y mpich libmpich-dev
    - ./build LIBS mpi-linux-x86_64 smp -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla || exit 1
    - make -C mpi-linux-x86_64-smp/tests TESTOPTS="+setcpuaffinity"
    - make -C mpi-linux-x86_64-smp/examples TESTOPTS="+setcpuaffinity"

  - os: osx
    name: "NetLRTS-Darwin"
    script:
    - ./build LIBS netlrts-darwin-x86_64 -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla || exit 1
    - make -C netlrts-darwin-x86_64/tests test TESTOPTS="++local"
    - make -C netlrts-darwin-x86_64/examples test TESTOPTS="++local"

  - os: windows
    name: "NetLRTS-Win"
    script:
    - choco upgrade -y cygwin cyg-get
    - cyg-get.bat cmake make gcc-core binutils libtool
    - cmd.exe //c C:\\tools\\cygwin\\bin\\bash.exe -l -c "cd build/UIUC-PPL/charm && src/arch/win/travis.sh ./build AMPI netlrts-win-x86_64 --without-romio -g --with-production -j3"
    - cmd.exe //c C:\\tools\\cygwin\\bin\\bash.exe -l -c "cd build/UIUC-PPL/charm && src/arch/win/travis.sh make -C netlrts-win-x86_64/tests -j3"
    - cmd.exe //c C:\\tools\\cygwin\\bin\\bash.exe -l -c "cd build/UIUC-PPL/charm && src/arch/win/travis.sh make -C netlrts-win-x86_64/examples -j3"
    - cmd.exe //c C:\\tools\\cygwin\\bin\\bash.exe -l -c "cd build/UIUC-PPL/charm && src/arch/win/travis.sh make -C netlrts-win-x86_64/benchmarks -j3"
    - cmd.exe //c C:\\tools\\cygwin\\bin\\bash.exe -l -c "cd build/UIUC-PPL/charm && src/arch/win/travis.sh make -C netlrts-win-x86_64/tests test TESTOPTS=++local"
    - cmd.exe //c C:\\tools\\cygwin\\bin\\bash.exe -l -c "cd build/UIUC-PPL/charm && src/arch/win/travis.sh make -C netlrts-win-x86_64/examples test TESTOPTS=++local"
    #- cmd.exe //c C:\\tools\\cygwin\\bin\\bash.exe -l -c "cd build/UIUC-PPL/charm && src/arch/win/travis.sh make -C netlrts-win-x86_64/benchmarks test TESTOPTS=++local"
