language: cpp

os: linux
dist: focal

# Necessary for Windows builds - do not convert LF to CRLF:
git:
  autocrlf: false

# before_install:
#   - |
#       if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
#         git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(\.rst$)|(^doc/)' || {
#           echo "Only docs were updated, stopping build process."
#           exit
#         }
#       fi

jobs:
  include:
  - os: linux
    arch: arm64
    name: "NetLRTS-Arm64"
    script:
    - sudo apt-get update
    - sudo apt-get install -y gfortran
    - ./build all-test netlrts-linux-arm8 -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla || exit 1
    - make -C netlrts-linux-arm8/tmp test TESTOPTS="++local"
  - os: linux
    arch: arm64
    name: "MPI-Arm64"
    script:
    - sudo apt-get update
    - sudo apt-get install -y gfortran mpich libmpich-dev
    - ./build all-test mpi-linux-arm8 -j3 --build-shared --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla || exit 1
    - make -C mpi-linux-arm8/tmp test
  - os: linux
    arch: ppc64le
    name: "NetLRTS-Power"
    script:
    - sudo apt-get update
    - sudo apt-get install -y gfortran
    - ./build all-test netlrts-linux-ppc64le -j3 --with-production --enable-error-checking --enable-lbuserdata -g -Werror=vla || exit 1
    - make -C netlrts-linux-ppc64le/tmp test TESTOPTS="++local"
