name: Trigger NAMD

on:
  pull_request:
  pull_request_review:
    types: [submitted]

jobs:
  check:
    if: ${{ (github.event_name == 'pull_request' && !github.event.pull_request.repo.fork) ||
            (github.event_name == 'pull_request_review' && github.event.pull_request.fork.repo &&
             github.event.review.state == 'approved') }}
    steps:
      - run: env
